#!/bin/sh
#
# Copyright (C) 2012 Treode, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To run the client, first build the assemlby jar:
#
#     $ sbt assembly
#
# Next move that jar into the same directory as this script, or adjust the class path in the
# command line below.  Then run the client as:
#
#     $ ./echo-client <server hostname>

export JAVA_HOME=${JAVA_HOME:-/usr/local/jdk1.7.0_07}
export SCALA_HOME=${SCALA_HOME:-/usr/local/scala-2.9.2}
exec ${SCALA_HOME}/bin/scala \
    -P:continuations:enable \
    -nocompdaemon \
    -classpath cps-example-assembly-0.1.jar \
    -J-XX:+HeapDumpOnOutOfMemoryError \
    "$0" "$@"
!#

import java.net.InetSocketAddress
import com.treode.cps.{CpsLiveConfig, CpsLiveKit, CpsLiveSocketKit}
import com.treode.cps.example.ExampleKit

val kit = new CpsLiveKit (new CpsLiveConfig {}) with CpsLiveSocketKit with ExampleKit
kit.launchClient (new InetSocketAddress (args (0), 4567))
